In [1]:
import sqlite3
import pandas as pd
import csv
import time
import numpy as np

База данных на данном этапе представлена двумя таблицами ps и sdss, содержащими в себе данные каталогов PS1 и SDSS DR12  о поле квадрата стороной $6^\circ$ с центром в $(243.9021249, 14.41539495)$:  ps1.csv, sdss12.csv

http://tapvizier.u-strasbg.fr/adql/

In [2]:
conn=sqlite3.connect('catalogs.db') 
cur=conn.cursor()

# cur.execute('SELECT * FROM sqlite_master').fetchall()

In [8]:
%%time 

ps_pand=pd.read_csv("ps1.csv", sep=',', low_memory=False)
ps_pand.astype(float)
ps_pand['ps_objID'].astype(int, copy = False)
ps_df = ps_pand[['ps_objID', 'ps_RA', 'ps_e_RA', 'ps_DE', 'ps_e_DE','ps_gmag', 'ps_e_gmag','ps_rmag', 'ps_e_rmag','ps_imag', 'ps_e_imag','ps_zmag', 'ps_e_zmag','ps_ymag', 'ps_e_ymag']]
ps_df

Wall time: 1.73 s

,ps_objID,ps_RA,ps_e_RA,ps_DE,ps_e_DE,ps_gmag,ps_e_gmag,ps_rmag,ps_e_rmag,ps_imag,ps_e_imag,ps_zmag,ps_e_zmag,ps_ymag,ps_e_ymag
0,124262408166872532,240.816706,0.0214,13.551750,0.0186,NaN,NaN,21.7728,0.1763,20.8666,0.0312,20.1391,0.0456,19.7513,0.0645
1,124262408223799720,240.822382,0.0720,13.557751,0.0720,NaN,NaN,NaN,NaN,21.9110,0.1282,20.3118,0.1573,NaN,NaN
2,124272408181530512,240.818139,0.0054,13.558309,0.0126,19.6112,0.0146,19.2861,0.0067,19.1697,0.0079,19.1277,0.0088,19.1135,0.0352
3,124272408244504730,240.824500,0.0675,13.561841,0.0758,NaN,NaN,21.9552,0.2101,21.4728,0.0417,21.2538,0.3378,NaN,NaN
4,124272408305508536,240.830455,0.0805,13.564970,0.0805,NaN,NaN,21.9373,0.1276,21.7675,0.0665,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1160771,128852470372759489,247.037319,0.0427,17.382430,0.1342,NaN,NaN,21.7465,0.0477,21.7044,0.0514,NaN,NaN,NaN,NaN
1160772,128852470266147058,247.026486,0.0909,17.380448,0.0909,NaN,NaN,21.5367,0.1453,21.2274,0.1151,NaN,NaN,NaN,NaN
1160773,128862470239084697,247.023949,0.0924,17.386888,0.0924,21.9786,0.1679,21.9937,0.0218,21.9408,0.2010,NaN,NaN,NaN,NaN
1160774,128862470236557391,247.023558,0.0747,17.388996,0.4903,22.0854,0.4006,21.7846,0.0433,21.7195,0.0511,NaN,NaN,NaN,NaN
1160775,128862470224209367,247.022273,0.0633,17.390452,0.2008,NaN,NaN,21.8664,0.1972,21.7753,0.0683,NaN,NaN,NaN,NaN

In [27]:
%%time

sdss_pand=pd.read_csv("sdss12.csv", sep=',', low_memory=False)
sdss_pand.astype(float)
sdss_pand['sdss_objID'].astype(int, copy = False)

sdss_df = sdss_pand[['sdss_objID', 'sdss_RA', 'sdss_e_RA', 'sdss_DE', 'sdss_e_DE', 'sdss_umag', 'sdss_e_umag', 'sdss_gmag', 'sdss_e_gmag','sdss_rmag', 'sdss_e_rmag','sdss_imag', 'sdss_e_imag','sdss_zmag', 'sdss_e_zmag']]
sdss_df

Wall time: 4.96 s

,sdss_objID,sdss_RA,sdss_e_RA,sdss_DE,sdss_e_DE,sdss_umag,sdss_e_umag,sdss_gmag,sdss_e_gmag,sdss_rmag,sdss_e_rmag,sdss_imag,sdss_e_imag,sdss_zmag,sdss_e_zmag
0,1237668335250244792,240.816713,0.059,13.551764,0.058,24.073,0.733,23.773,0.318,22.364,0.130,20.935,0.054,20.119,0.101
1,1237667783395050842,240.816739,0.077,13.551767,0.055,25.720,0.526,24.334,0.429,22.119,0.113,20.874,0.063,20.147,0.109
2,1237665565007938478,240.822368,0.083,13.557720,0.112,25.075,0.903,24.963,0.616,22.428,0.148,21.948,0.146,22.115,0.499
3,1237668335250244424,240.822405,0.119,13.557708,0.103,25.713,0.536,23.352,0.244,22.606,0.170,21.921,0.133,21.385,0.310
4,1237667783395050451,240.822387,0.251,13.557707,0.193,23.671,0.849,24.396,0.633,22.260,0.188,21.502,0.160,21.707,0.597
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2265929,1237665537081541552,247.023583,0.089,17.389019,0.088,24.172,1.271,22.337,0.135,21.864,0.129,21.533,0.164,21.192,0.445
2265930,1237665180608889579,247.023564,0.121,17.389063,0.127,25.178,1.112,22.691,0.186,21.900,0.138,21.614,0.185,21.126,0.407
2265931,1237665537081541846,247.022311,0.088,17.390563,0.084,25.999,0.475,23.867,0.328,22.372,0.133,21.915,0.147,21.713,0.428
2265932,1237665230523598544,247.016450,0.188,17.389549,0.189,21.295,0.332,22.378,0.374,21.982,0.407,20.466,0.157,19.619,0.282
2265933,1237665537081542081,247.016445,0.259,17.389609,0.349,21.315,0.530,21.426,0.238,21.886,0.541,20.012,0.177,20.090,0.724

In [28]:
ps_df.to_sql(name='ps', con=conn, if_exists='replace', index=False)

In [29]:
sdss_df.to_sql(name='sdss', con=conn, if_exists='replace', index=False)

In [30]:
conn.commit()

In [31]:
conn.close()